'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TB_CONTA
    Public Property COD_CONTA As Decimal
    Public Property DESCRICAO As String
    Public Property TIPO As String
    Public Property OBSERVACAO As String
    Public Property COD_CONTA_RAIZ As Nullable(Of Decimal)
    Public Property NUM_ORDEM As Nullable(Of Short)
    Public Property VAL_COR As String

    Public Overridable Property TB_TITULO As ICollection(Of TB_TITULO) = New HashSet(Of TB_TITULO)
    Public Overridable Property TB_CONTA1 As ICollection(Of TB_CONTA) = New HashSet(Of TB_CONTA)
    Public Overridable Property TB_CONTA2 As TB_CONTA
    Public Overridable Property TB_MOVIMENTO_CARTAO As ICollection(Of TB_MOVIMENTO_CARTAO) = New HashSet(Of TB_MOVIMENTO_CARTAO)
    Public Overridable Property TB_CARTAO As ICollection(Of TB_CARTAO) = New HashSet(Of TB_CARTAO)

End Class
