'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TB_LANCAMENTO
    Public Property COD_LANCAMENTO As Decimal
    Public Property COD_TITULO As Decimal
    Public Property VALOR As Decimal
    Public Property DATA As Date
    Public Property OBSERVACAO As String

    Public Overridable Property TB_TITULO As TB_TITULO

End Class
