'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TB_MOVIMENTO_CARTAO
    Public Property SEQ_MOVIMENTO As Decimal
    Public Property COD_CARTAO As Short
    Public Property COD_CONTA As Decimal
    Public Property DESCRICAO As String
    Public Property DAT_MOVIMENTO As Date
    Public Property VALOR As Decimal
    Public Property NUM_PARCELA As Nullable(Of Short)
    Public Property OBSERVACAO As String
    Public Property DAT_CADASTRO As Date
    Public Property COD_TITULO As Decimal
    Public Property COD_TITULO_DESPESA As Nullable(Of Decimal)

    Public Overridable Property TB_CARTAO As TB_CARTAO
    Public Overridable Property TB_CONTA As TB_CONTA
    Public Overridable Property TB_TITULO As TB_TITULO
    Public Overridable Property TB_TITULO1 As TB_TITULO

End Class
