'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TB_PARCELA
    Public Property SEQ_PARCELA As Decimal
    Public Property SEQ_PARCELAMENTO As Decimal
    Public Property NUM_PARCELA As Short
    Public Property COD_TITULO As Nullable(Of Decimal)
    Public Property OBSERVACAO As String
    Public Property DAT_CADASTRO As Date
    Public Property VALOR As Decimal
    Public Property DAT_VENCIMENTO As Date

    Public Overridable Property TB_PARCELAMENTO As TB_PARCELAMENTO
    Public Overridable Property TB_TITULO As TB_TITULO

End Class
