'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TB_PARCELAMENTO
    Public Property SEQ_PARCELAMENTO As Decimal
    Public Property DESCRICAO As String
    Public Property QTD_PARCELA As Short
    Public Property COD_TITULO As Nullable(Of Decimal)
    Public Property DAT_INICIO As Date
    Public Property DAT_CADASTRO As Date
    Public Property OBSERVACAO As String
    Public Property VALOR As Decimal

    Public Overridable Property TB_PARCELA As ICollection(Of TB_PARCELA) = New HashSet(Of TB_PARCELA)
    Public Overridable Property TB_TITULO As TB_TITULO

End Class
