'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TB_TITULO
    Public Property COD_TITULO As Decimal
    Public Property DESCRICAO As String
    Public Property DAT_VENCIMENTO As Date
    Public Property VALOR As Decimal
    Public Property COD_CONTA As Decimal
    Public Property OBSERVACAO As String
    Public Property NUM_PARCELA As Nullable(Of Short)
    Public Property DAT_CADASTRO As Nullable(Of Date)
    Public Property COD_TITULO_ORIGEM As Nullable(Of Decimal)
    Public Property DAT_PLANEJAMENTO As Nullable(Of Date)

    Public Overridable Property TB_CONTA As TB_CONTA
    Public Overridable Property TB_LANCAMENTO As ICollection(Of TB_LANCAMENTO) = New HashSet(Of TB_LANCAMENTO)
    Public Overridable Property TB_TITULO1 As ICollection(Of TB_TITULO) = New HashSet(Of TB_TITULO)
    Public Overridable Property TB_TITULO2 As TB_TITULO
    Public Overridable Property TB_MOVIMENTO_CARTAO As ICollection(Of TB_MOVIMENTO_CARTAO) = New HashSet(Of TB_MOVIMENTO_CARTAO)
    Public Overridable Property TB_MOVIMENTO_CARTAO1 As ICollection(Of TB_MOVIMENTO_CARTAO) = New HashSet(Of TB_MOVIMENTO_CARTAO)
    Public Overridable Property TB_PARCELA As ICollection(Of TB_PARCELA) = New HashSet(Of TB_PARCELA)
    Public Overridable Property TB_PARCELAMENTO As ICollection(Of TB_PARCELAMENTO) = New HashSet(Of TB_PARCELAMENTO)

End Class
