'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_parcelamento
    Public Property seq_parcelamento As Decimal
    Public Property descricao As String
    Public Property valor As Decimal
    Public Property qtd_parcela As Short
    Public Property dat_inicio As Date
    Public Property qtd_parcela_paga As Nullable(Of Integer)
    Public Property valor_pago As Nullable(Of Decimal)
    Public Property qtd_mes As Nullable(Of Integer)
    Public Property situacao As Nullable(Of Integer)

End Class
