'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_titulo
    Public Property DESC_RAIZ As String
    Public Property DESC_CONTA As String
    Public Property COD_LANCAMENTO As Nullable(Of Decimal)
    Public Property COD_CONTA As Decimal
    Public Property TIPO As String
    Public Property COD_TITULO As Decimal
    Public Property DAT_CADASTRO As Nullable(Of Date)
    Public Property DAT_VENCIMENTO As Date
    Public Property DESCRICAO As String
    Public Property NUM_PARCELA As Nullable(Of Short)
    Public Property OBSERVACAO As String
    Public Property VALOR As Decimal
    Public Property VAL_PAGO As Decimal
    Public Property VAL_TITULO As Decimal
    Public Property DAT_PAGAMENTO As Nullable(Of Date)
    Public Property VAL_RESTANTE As Nullable(Of Decimal)
    Public Property NUM_ORDEM As Short
    Public Property VAL_COR As String
    Public Property cod_conta_raiz As Decimal
    Public Property seq_parcela As Nullable(Of Decimal)
    Public Property DAT_PLANEJAMENTO As Nullable(Of Date)

End Class
